export type Book = {
  name: string;
  slug: string;
  chapters: number;
  usfm: string;
};

export const BOOKS: Book[] = [
  { name: 'Genesis',        slug: 'genesis',        chapters: 50,  usfm: 'GEN' },
  { name: 'Exodus',         slug: 'exodus',         chapters: 40,  usfm: 'EXO' },
  { name: 'Leviticus',      slug: 'leviticus',      chapters: 27,  usfm: 'LEV' },
  { name: 'Numbers',        slug: 'numbers',        chapters: 36,  usfm: 'NUM' },
  { name: 'Deuteronomy',    slug: 'deuteronomy',    chapters: 34,  usfm: 'DEU' },
  { name: 'Joshua',         slug: 'joshua',         chapters: 24,  usfm: 'JOS' },
  { name: 'Judges',         slug: 'judges',         chapters: 21,  usfm: 'JDG' },
  { name: 'Ruth',           slug: 'ruth',           chapters: 4,   usfm: 'RUT' },
  { name: '1 Samuel',       slug: '1+samuel',       chapters: 31,  usfm: '1SA' },
  { name: '2 Samuel',       slug: '2+samuel',       chapters: 24,  usfm: '2SA' },
  { name: '1 Kings',        slug: '1+kings',        chapters: 22,  usfm: '1KI' },
  { name: '2 Kings',        slug: '2+kings',        chapters: 25,  usfm: '2KI' },
  { name: '1 Chronicles',   slug: '1+chronicles',   chapters: 29,  usfm: '1CH' },
  { name: '2 Chronicles',   slug: '2+chronicles',   chapters: 36,  usfm: '2CH' },
  { name: 'Ezra',           slug: 'ezra',           chapters: 10,  usfm: 'EZR' },
  { name: 'Nehemiah',       slug: 'nehemiah',       chapters: 13,  usfm: 'NEH' },
  { name: 'Esther',         slug: 'esther',         chapters: 10,  usfm: 'EST' },
  { name: 'Job',            slug: 'job',            chapters: 42,  usfm: 'JOB' },
  { name: 'Psalms',         slug: 'psalms',         chapters: 150, usfm: 'PSA' },
  { name: 'Proverbs',       slug: 'proverbs',       chapters: 31,  usfm: 'PRO' },
  { name: 'Ecclesiastes',   slug: 'ecclesiastes',   chapters: 12,  usfm: 'ECC' },
  { name: 'Song of Solomon',slug: 'song+of+solomon',chapters: 8,   usfm: 'SNG' },
  { name: 'Isaiah',         slug: 'isaiah',         chapters: 66,  usfm: 'ISA' },
  { name: 'Jeremiah',       slug: 'jeremiah',       chapters: 52,  usfm: 'JER' },
  { name: 'Lamentations',   slug: 'lamentations',   chapters: 5,   usfm: 'LAM' },
  { name: 'Ezekiel',        slug: 'ezekiel',        chapters: 48,  usfm: 'EZK' },
  { name: 'Daniel',         slug: 'daniel',         chapters: 12,  usfm: 'DAN' },
  { name: 'Hosea',          slug: 'hosea',          chapters: 14,  usfm: 'HOS' },
  { name: 'Joel',           slug: 'joel',           chapters: 3,   usfm: 'JOL' },
  { name: 'Amos',           slug: 'amos',           chapters: 9,   usfm: 'AMO' },
  { name: 'Obadiah',        slug: 'obadiah',        chapters: 1,   usfm: 'OBA' },
  { name: 'Jonah',          slug: 'jonah',          chapters: 4,   usfm: 'JON' },
  { name: 'Micah',          slug: 'micah',          chapters: 7,   usfm: 'MIC' },
  { name: 'Nahum',          slug: 'nahum',          chapters: 3,   usfm: 'NAM' },
  { name: 'Habakkuk',       slug: 'habakkuk',       chapters: 3,   usfm: 'HAB' },
  { name: 'Zephaniah',      slug: 'zephaniah',      chapters: 3,   usfm: 'ZEP' },
  { name: 'Haggai',         slug: 'haggai',         chapters: 2,   usfm: 'HAG' },
  { name: 'Zechariah',      slug: 'zechariah',      chapters: 14,  usfm: 'ZEC' },
  { name: 'Malachi',        slug: 'malachi',        chapters: 4,   usfm: 'MAL' },
  { name: 'Matthew',        slug: 'matthew',        chapters: 28,  usfm: 'MAT' },
  { name: 'Mark',           slug: 'mark',           chapters: 16,  usfm: 'MRK' },
  { name: 'Luke',           slug: 'luke',           chapters: 24,  usfm: 'LUK' },
  { name: 'John',           slug: 'john',           chapters: 21,  usfm: 'JHN' },
  { name: 'Acts',           slug: 'acts',           chapters: 28,  usfm: 'ACT' },
  { name: 'Romans',         slug: 'romans',         chapters: 16,  usfm: 'ROM' },
  { name: '1 Corinthians',  slug: '1+corinthians',  chapters: 16,  usfm: '1CO' },
  { name: '2 Corinthians',  slug: '2+corinthians',  chapters: 13,  usfm: '2CO' },
  { name: 'Galatians',      slug: 'galatians',      chapters: 6,   usfm: 'GAL' },
  { name: 'Ephesians',      slug: 'ephesians',      chapters: 6,   usfm: 'EPH' },
  { name: 'Philippians',    slug: 'philippians',    chapters: 4,   usfm: 'PHP' },
  { name: 'Colossians',     slug: 'colossians',     chapters: 4,   usfm: 'COL' },
  { name: '1 Thessalonians',slug: '1+thessalonians',chapters: 5,   usfm: '1TH' },
  { name: '2 Thessalonians',slug: '2+thessalonians',chapters: 3,   usfm: '2TH' },
  { name: '1 Timothy',      slug: '1+timothy',      chapters: 6,   usfm: '1TI' },
  { name: '2 Timothy',      slug: '2+timothy',      chapters: 4,   usfm: '2TI' },
  { name: 'Titus',          slug: 'titus',          chapters: 3,   usfm: 'TIT' },
  { name: 'Philemon',       slug: 'philemon',       chapters: 1,   usfm: 'PHM' },
  { name: 'Hebrews',        slug: 'hebrews',        chapters: 13,  usfm: 'HEB' },
  { name: 'James',          slug: 'james',          chapters: 5,   usfm: 'JAS' },
  { name: '1 Peter',        slug: '1+peter',        chapters: 5,   usfm: '1PE' },
  { name: '2 Peter',        slug: '2+peter',        chapters: 3,   usfm: '2PE' },
  { name: '1 John',         slug: '1+john',         chapters: 5,   usfm: '1JN' },
  { name: '2 John',         slug: '2+john',         chapters: 1,   usfm: '2JN' },
  { name: '3 John',         slug: '3+john',         chapters: 1,   usfm: '3JN' },
  { name: 'Jude',           slug: 'jude',           chapters: 1,   usfm: 'JUD' },
  { name: 'Revelation',     slug: 'revelation',     chapters: 22,  usfm: 'REV' },
];
